In [ ]:
# ** = very important
# **train_test_split method = splits whole data into train_X,test_x,train_y,test_y (2 parts splitting = train and test)
# kFold splits method = splits whole data into k different groups specifically
# Stratified k fold splitting method = splits whole data into k different groups randomly
# **Cross Val Score method = splits whole data internally into "cv" parts and gives score of model for each part 
# **Grid Scerach CV methpd = splits whole data internally into "cv" and predicts them with different other parameters "each combination of params" i.e hyperparameter tunning
# Randomized Search CV method = splits whole data internally into "cv" and predicts them with different other parameters "randomly selects combination of params" i.e random hyperparameter tunning

In [39]:
from sklearn import datasets
from sklearn.svm import SVC

In [40]:
iris = datasets.load_iris()
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [41]:
import pandas as pd
df = pd.DataFrame(iris.data,columns = iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [42]:
df["flower"] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0       0  
1       0  
2       0  
3       0  
4       0

In [43]:
df["flower"] = df["flower"].apply(lambda x: iris.target_names[x])  
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

# Train_Test_Split

In [44]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.3)

In [45]:
model = SVC(kernel = "rbf" , C=30,gamma="auto")
model.fit(X_train,y_train)
model.score(X_test,y_test)   # but this score varies based on sample (changing)

0.9333333333333333

# cross_val_score

In [46]:
from sklearn.model_selection import cross_val_score

In [47]:
cross_val_score(SVC(kernel="linear",C=10,gamma="auto"),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [48]:
cross_val_score(SVC(kernel="rbf",C=10,gamma="auto"),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [49]:
cross_val_score(SVC(kernel="rbf",C=20,gamma="auto"),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

# Using For Loop for cross_val_score

In [50]:
import numpy as np
kernels = ["rbf","linear"]
C = [1,10,20]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(SVC(kernel=kval,C=cval,gamma="auto"),iris.data,iris.target,cv=5)
        avg_scores[kval + "_" + str(cval)] = np.average(cv_scores)
        
avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

# GridSearchCV (does the same exact thing as in cell above)

In [55]:
from sklearn.model_selection import GridSearchCV

param_grid ={
    'C': [1,10,20],
    "kernel": ["rbf","linear"]
        }

clf = GridSearchCV(SVC(gamma="auto"),param_grid,cv = 5,return_train_score=False)

clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00127172, 0.00069618, 0.00189242, 0.00178752, 0.00178566,
        0.00139742]),
 'std_fit_time': array([0.00040149, 0.0007655 , 0.00049471, 0.00039485, 0.00039844,
        0.00048956]),
 'mean_score_time': array([0.00060382, 0.00098519, 0.00060368, 0.00042939, 0.00079846,
        0.00059929]),
 'std_score_time': array([0.00037141, 0.00063083, 0.00049311, 0.00052621, 0.00040039,
        0.00048933]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [56]:
df2 = pd.DataFrame(clf.cv_results_)
df2.head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001272      0.000401         0.000604        0.000371       1   
1       0.000696      0.000766         0.000985        0.000631       1   
2       0.001892      0.000495         0.000604        0.000493      10   
3       0.001788      0.000395         0.000429        0.000526      10   
4       0.001786      0.000398         0.000798        0.000400      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5

In [57]:
df2[["param_C","param_kernel","mean_test_score"]]   # hypertuning done internally!!!

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [58]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits

In [63]:
clf.best_estimator_

SVC(C=1, gamma='auto')

In [66]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [68]:
clf.best_score_

0.9800000000000001

# RandomizedSearchCV (for random set of param_grid )
##  Good to tackle computation problem of GridSearchCV

In [73]:
from sklearn.model_selection import RandomizedSearchCV

param_grid ={
    'C': [1,10,20],
    "kernel": ["rbf","linear"]
        }

rs = RandomizedSearchCV(SVC(gamma="auto"),param_grid,cv = 5,return_train_score=False,n_iter = 2)

rs.fit(iris.data,iris.target)
# rs.cv_results_
df3 = pd.DataFrame(rs.cv_results_)
df3.head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.000878      0.000206         0.001001        0.000061       linear   
1       0.001326      0.000984         0.000588        0.000544          rbf   

  param_C                        params  split0_test_score  split1_test_score  \
0       1  {'kernel': 'linear', 'C': 1}           0.966667                1.0   
1       1     {'kernel': 'rbf', 'C': 1}           0.966667                1.0   

   split2_test_score  split3_test_score  split4_test_score  mean_test_score  \
0           0.966667           0.966667                1.0             0.98   
1           0.966667           0.966667                1.0             0.98   

   std_test_score  rank_test_score  
0         0.01633                1  
1         0.01633                1

In [74]:
df3[["param_C","param_kernel","mean_test_score"]]

param_C param_kernel  mean_test_score
0       1       linear             0.98
1       1          rbf             0.98

# Comparing 3 different models performance

In [75]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [79]:
model_params = {
    'SVC': {
        'model': SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [80]:
scores = []

for model_name, np in model_params.items():
    clf = GridSearchCV(np["model"],np["params"],cv=5,return_train_score = False)
    clf.fit(iris.data,iris.target)
    scores.append({
        "model" : model_name,
        "best_score" : clf.best_score_,
        "best_params" : clf.best_params_
    })

In [81]:
scores

[{'model': 'SVC',
  'best_score': 0.9800000000000001,
  'best_params': {'C': 1, 'kernel': 'rbf'}},
 {'model': 'random_forest',
  'best_score': 0.9533333333333334,
  'best_params': {'n_estimators': 10}},
 {'model': 'logistic_regression',
  'best_score': 0.9666666666666668,
  'best_params': {'C': 5}}]

In [83]:
df4 = pd.DataFrame(scores,columns=["model","best_params","best_score"])
df4

model  best_score  best_score
0                  SVC    0.980000    0.980000
1        random_forest    0.953333    0.953333
2  logistic_regression    0.966667    0.966667