In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")
df

area   bedrooms  age   price
0   2600       3.0   20  550000
1   3000       4.0   15  565000
2   3200       NaN   18  610000
3   3600       3.0   30  595000
4   4000       5.0    8  760000

In [3]:
# filling missing data in bedroom col

import math
median_bedrooms = math.floor(df.bedrooms.median())  # to get only int and not float or decimal no.
median_bedrooms

3

In [4]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df  # updated df

area   bedrooms  age   price
0   2600       3.0   20  550000
1   3000       4.0   15  565000
2   3200       3.0   18  610000
3   3600       3.0   30  595000
4   4000       5.0    8  760000

In [5]:
df.columns

Index(['area ', 'bedrooms', 'age', 'price'], dtype='object')

In [6]:
reg = linear_model.LinearRegression()
reg.fit(df[['area ', 'bedrooms', 'age']],df.price)   # reg.fit(X,y)

# copy paste the names of column from df.columns o/p as if there is 
# some space or syntax erro in col name then there will be error in further code

LinearRegression()

In [7]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [8]:
reg.intercept_

383724.9999999998

In [13]:
reg.predict([[3000,3,40]])

array([444400.])

In [14]:
#  calc 
137.25*3000 + -26025*3 + -6825*40 + 383724.9999999998

444399.9999999998

In [17]:
reg.predict([[2500,4,5]])

array([588625.])

## With Train and Split Data

In [43]:
# almost same as done in linear regression test and train (see and refer that please)