In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [4]:
df = pd.read_csv("homeprices.csv")

In [5]:
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [6]:
model = linear_model.LinearRegression()

model.fit(df[['area']],df.price)

LinearRegression()

In [7]:
model.coef_

array([135.78767123])

In [8]:
model.intercept_

180616.43835616432

In [9]:
model.predict([[5000]])

array([859554.79452055])

## Pickle method of saving model (for less no. of numpy arrrays in datasets and less complexitiy)

In [10]:
import pickle

In [15]:
# with open("model_pickle","wb") as f:  # wb = witing in binary mode  
#     pickle.dump(model,f)

In [15]:
# easy syntax............
# another syntax of pickle:

# pickle.dump(model,open("model_pickle.pkl","wb"))   or 

pickle.dump(model,open("model_pickle","wb"))

In [17]:
# with open("model_pickle","rb") as f: #rb = read mode in binary form 
#      np = pickle.load(f)                # can send this " model_pickle" file to anyone to share the working trained model

In [16]:
# easy syntax to load the pickle file

np = pickle.load(open("model_pickle","rb"))

In [17]:
np.predict([[5000]])

array([859554.79452055])

## Sklearn Joblib modules (for more complex datasets ....)

In [23]:
import joblib  # or   from sklearn.externals import joblib

In [24]:
joblib.dump(model,"model_joblib")   # can send this "model_joblib" file to anyone to share the working trained model

['model_joblib']

In [25]:
mj = joblib.load("model_joblib")

In [26]:
mj.predict([[5000]])

array([859554.79452055])

In [27]:
mj.coef_

array([135.78767123])

In [28]:
mj.intercept_

180616.43835616432