In [43]:
# Kfold and stratified k folds splits the data set i.e test and train data into k different groups -> k is given by user

# Cross validation does it internally (internal splitting) and gives us score -> cv is given by user

# Both are doing same thing almost but have diffeent tecjhnique internally and have different syntax

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits= load_digits()

## calc the accuracy of model Using Train_Test_split 

In [2]:
from sklearn.model_selection import train_test_split
X_train,X_test ,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [4]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9888888888888889

In [10]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9465776293823038

In [11]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [12]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9232053422370617

In [13]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9666110183639399

In [14]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9315525876460768

## calc accuracy of model using K_Fold method

In [15]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)   # write arguments with proper syntac (s at the end, capital letters etc...)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [16]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data,digits.target):
    X_train,X_test ,y_train,y_test = digits.data[train_index] ,digits.data[test_index] ,digits.target[train_index] ,digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(),X_train,X_test ,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test ,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=1000),X_train,X_test ,y_train,y_test))
    

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

In [17]:
print(scores_l)
print(scores_svm)
print(scores_rf)

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]
[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]
[0.9432387312186978, 0.9582637729549248, 0.9248747913188647]


In [18]:
 # illustrating using kf of KFold
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


## using Stratified_K_Fold 
## (to get folds from each categories)

In [38]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)
folds

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [39]:
# real "digits" data using folds (stratified)

scores_l2 = []
scores_svm2 = []
scores_rf2 = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train,X_test ,y_train,y_test = digits.data[train_index] ,digits.data[test_index] ,digits.target[train_index] ,digits.target[test_index]
    scores_l2.append(get_score(LogisticRegression(),X_train,X_test ,y_train,y_test))
    scores_svm2.append(get_score(SVC(),X_train,X_test ,y_train,y_test))
    scores_rf2.append(get_score(RandomForestClassifier(n_estimators=1000),X_train,X_test ,y_train,y_test))
    

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

In [40]:
scores_l2

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [41]:
scores_svm2

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [42]:
scores_rf2

[0.9432387312186978, 0.9599332220367279, 0.9232053422370617]

## using cross_val_score (most efficient and simple in syntax)
## implements the same way like kfold and stratified kfold internally

In [48]:
from sklearn.model_selection import cross_val_score

In [51]:
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=3)

D:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result

array([0.92153589, 0.94156928, 0.91652755])

In [52]:
cross_val_score(SVC(),digits.data,digits.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [61]:
cross_val_score(RandomForestClassifier(n_estimators=1000),digits.data,digits.target,cv=3)

array([0.94490818, 0.96160267, 0.92654424])