In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

# basics


In [3]:
# 1-D array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
# 1-D array
b = np.array([[1.1,8.8,5.5],[1.2,3.4,5.6],[1.2,3.4,5.6]])
print(b)

[[1.1 8.8 5.5]
 [1.2 3.4 5.6]
 [1.2 3.4 5.6]]


In [5]:
# 3-D array
c = np.array([
             [[1.1,8.8,5.5,0.9],[1.2,3.4,5.6,0.8],[1.2,3.4,5.6,0.9]],
             [[1.1,8.8,5.5,0.8],[1.2,3.4,5.6,0.99],[1.2,3.4,5.6,0.8]]
            ])
print(c)

[[[1.1  8.8  5.5  0.9 ]
  [1.2  3.4  5.6  0.8 ]
  [1.2  3.4  5.6  0.9 ]]

 [[1.1  8.8  5.5  0.8 ]
  [1.2  3.4  5.6  0.99]
  [1.2  3.4  5.6  0.8 ]]]


In [6]:
#Get Dimension
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [7]:
# Get shape
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(3, 3)
(2, 3, 4)


In [8]:
import numpy as np

a = np.array([1,2,3], dtype='int32')
print(a)

b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]],dtype=int)
print(b)

# Get Dimension
print(a.ndim)

[1 2 3]
[[9 8 7]
 [6 5 4]]
1


In [9]:
# Get Shape
print(b.shape)

# Get Type
print(a.dtype)

# Get Size of each item
print(a.itemsize)

# get size of numpyarray i.e number of elements in numpy array
print(a.size)

# Get total size
print(a.nbytes)   # (itemsize * size)


(2, 3)
int32
4
3
12


In [10]:
#Accessing/Changing specific elements, rows, columns, etc
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

# Get a specific element [r, c]
print(a[1, 5])

# Get a specific row 
print(a[0, :])

# Get a specific column
print(a[:, 2])

# Getting a little more fancy [startindex:endindex:stepsize]
print(a[0, 1:-1:2])    
# MIMPORTANT 0 = first row , 1 =  first element of first row i.e "2" , -1 means last elemnt of first row = "7" and 2 means stepsize 
# which means in 1st row , start from 2 to 7 and skip every one element between this interval

a[1,5] = 20
print(a)

a[:,2] = [99,77] # changes all rows of 2nd col to 99 and 77 respectively one after another
print(a) 

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2 99  4  5  6  7]
 [ 8  9 77 11 12 20 14]]


In [11]:
#*3-d example

b = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(b)

# Get specific element 
print(b[0,1,1])

# replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4
[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [12]:
#Initializing Different Types of Arrays
# All 0s matrix
print(np.zeros((2,3)))
print("\n")

# All 1s matrix
print(np.ones((4,2,2), dtype='int32'))
print("\n")

# Any other number
print(np.full((2,2), 99))
print("\n")

# Any other number (full_like)
print(np.full_like(a, 4))
print("\n")
# or
print(np.full(a.shape,4))
print("\n")

# Random decimal numbers
print(np.random.rand(4,2))
print("\n")

# Random Integer values
print(np.random.randint(-4,4, size=(3,3))) #range of random nos. is -4 to 3(can come) 


[[0. 0. 0.]
 [0. 0. 0.]]


[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


[[99 99]
 [99 99]]


[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


[[0.07221252 0.65550602]
 [0.35725665 0.19077736]
 [0.42197353 0.22706796]
 [0.30213826 0.91770132]]


[[-3 -3  3]
 [-2  2 -1]
 [-4 -3 -4]]


In [13]:
# The identity matrix
np.identity((5),dtype=int)


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [14]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

r2 = np.repeat(arr,3, axis=1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [15]:
#exercise
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
# Be careful when copying arrays!!!
a = np.array([1,2,3])

print("way : 1")
b = a 
# when we copy by using assignment operator, if we make changes in copy, it will automatically make changes in original as well

b[0] = 100
print(b)
print(a)

print("\n way : 2")
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)

way : 1
[100   2   3]
[100   2   3]

 way : 2
[100   2   3]
[1 2 3]


In [17]:
#Mathematics
a = np.array([1,2,3,4])
print(a)

print(a + 2)

print(a - 2)

print(a * 2)

print(a / 2)

b = np.array([1,0,1,0])
print(a + b)
print(a ** 2)

# Take the sin/cos
print(np.cos(a))

# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[2 2 4 4]
[ 1  4  9 16]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [18]:
# Linear Algebra
a = np.ones((2,3))
print(a)

b = np.full((3,2), 5)
print(b)

print(np.matmul(a,b))  # matmul = matrix multiplication

# Find the determinant
c = np.identity(3)
print(np.linalg.det(c))    # linalg.det = to find determinant of matries

## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[15. 15.]
 [15. 15.]]
1.0


In [19]:
# Statistics
stats = np.array([[1,2,3],[4,5,6]])            # ------> axis = 1
print(stats)                                   # |
                                               # |
print(np.min(stats))                           # |
                                               #\|/ axis = 0
print(np.max(stats, axis=1))

print(np.sum(stats, axis=0))

# or

print(stats.sum(axis=0))
print(stats.min(axis=0))
print(stats.max(axis=0))
print(stats.cumsum())
print(stats.prod())
print(stats.cumprod())

print(np.power(stats[0],stats[1]))   # 1^4,2^5,3^6


[[1 2 3]
 [4 5 6]]
1
[3 6]
[5 7 9]
[5 7 9]
[1 2 3]
[4 5 6]
[ 1  3  6 10 15 21]
720
[  1   2   6  24 120 720]
[  1  32 729]


In [20]:
# Reorganizing Arrays
before = np.array([[1,2,3,4],[5,6,7,8]])  # 4 X 2
print(before)

# after = before.reshape((1,8))
after = before.reshape((8,1)) 

# after = before.reshape(()) #Error: other any n X m will give error as n*m = no. of elements in the array (1-D,2-D,3-D....-D)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [21]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [23]:
# Miscellaneous

# Load Data from File
# filedata = np.genfromtxt('data.txt', delimiter=',')
# filedata = filedata.astype('int32')
# print(filedata)

# Boolean Masking and Advanced Indexing
# (~((filedata > 50) & (filedata < 100)))

In [24]:
a = np.arange(10)   # using range function of python as arange here to give nos. in continuous range order
print(a.ndim)
print(a.shape)
print(a)

b = a.reshape(2,5) 
# "reshape" function reshapes the array but doesn't make changes to the original one but assigns the reshaped array to new array or the old one as weel

print(b.ndim)
print(b.shape)
print(b)

print(a.ndim)
print(a.shape)
print(a)

1
(10,)
[0 1 2 3 4 5 6 7 8 9]
2
(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]
1
(10,)
[0 1 2 3 4 5 6 7 8 9]


In [25]:
linspace_arr = np.linspace(1,5,10)  # divides the range 1 to 5 into 10 equal parts 
print(linspace_arr)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


# reshaping and ravelling

In [26]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
arr.reshape(3,33) # shapes in N X M form    
# doesn't modify the original array
# (here we r printing only one thing so we can write like this else we have to write like new_arry = old_array.reshape(m,n))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [28]:
print(arr.shape)
print(arr.ravel()) # makes any shaped array - flatten !!   # doesn't modify the original array

(99,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [29]:
one = np.array([1,2,7,0,5,3])
print(one.argmax())  # returns the index of max and min nos.
print(one.argmin())

2
3


In [30]:
one.argsort() # sort the array in increasing order of their indexes

array([3, 0, 1, 5, 4, 2], dtype=int64)

In [31]:
two = one.reshape(2,3)
print(two)
print(two.argmax(axis=0))
print(two.argmax(axis=1))
print(two.argmin(axis=0))
print(two.argmin(axis=1))


[[1 2 7]
 [0 5 3]]
[0 1 0]
[2 1]
[1 0 1]
[0 0]


In [32]:
hetvi = np.arange(15)
print(hetvi)
np.where(hetvi>2)   # gives indexes of the numbers that are greater than 2 or that satisfies the where condition

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


(array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14], dtype=int64),)

In [33]:
hetvi2D = hetvi.reshape(5,3)
np.where(hetvi2D>2) 
# shows indexes of one axis and then other axis that satisfies where condition like (1,0),(1,1),(1,2),(2,0),(2,1)....
# all except(0,0),(0,1),(0,2)

(array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [34]:
s = np.array([99,91,90,99.8,99.7])
print(s)
print(s.min())  # instead of indexes these functions gives min and max numbers(elements) of array
print(s.max())

[99.  91.  90.  99.8 99.7]
90.0
99.8


In [35]:
array = np.array([[1,2,3],[4,5,6]])
print(array)
print(array.T)  # transpose of matrix

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [53]:
hetvi = np.arange(16)
print(hetvi)
hetvi2 = hetvi.reshape(2,8)
print(hetvi2)
print(hetvi2.shape)
print(hetvi2[0],hetvi2[1])  #Imp  # by writing like this we get 0 as first row and 1 as second row
print(hetvi2[-1])         # prints last row 
print(hetvi2[0,1],hetvi2[1,1]) #Imp
print(hetvi2[-1,-1])     #Imp last = -1 last second = -2....

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
(2, 8)
[0 1 2 3 4 5 6 7] [ 8  9 10 11 12 13 14 15]
[ 8  9 10 11 12 13 14 15]
1 9
15


# Datatypes 

In [48]:
arr = np.array([[1,2,3],[1,2,3]])
print(arr)
print(arr.dtype.name)           # default int is of 32 bytes


arr1 = np.array([[1,2,3],[1,2,3]], dtype = float)
print(arr1)                    
print(arr1.dtype.name)          # default float is of 64 bytes

arr2 = np.array([[1,2,3],[1,2,3]], dtype = np.int32)
print(arr2)
print(arr2.dtype.name)     # ---> command to know the name of datatype

arr3 = np.array([[1,2,3],[1,2,3]], dtype = np.int64)
print(arr3)
print(arr3.dtype.name)


arr4 = np.array([[1,2,3],[1,2,3]], dtype = np.float32)
print(arr4)
print(arr4.dtype.name)

arr5= np.array([[1,2,3],[1,2,3]], dtype = np.int16)
print(arr5)
print(arr5.dtype.name)

c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)
print(c.dtype.name)       # --------> default complex is of 128 bytes

[[1 2 3]
 [1 2 3]]
int32
[[1. 2. 3.]
 [1. 2. 3.]]
float64
[[1 2 3]
 [1 2 3]]
int32
[[1 2 3]
 [1 2 3]]
int64
[[1. 2. 3.]
 [1. 2. 3.]]
float32
[[1 2 3]
 [1 2 3]]
int16
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
complex128


In [38]:

# np.int16 Integer (-32768 to 32767)

# np.int32 Integer (-2147483648 to 2147483647)

# np.int64 Integer (-9223372036854775808 to 9223372036854775887)

array_a = np.array( [32766, 32767, 32768],dtype = np.int16)
print(array_a)    # bcoz 32768 is out of int16 bound therefore it will give negative no. to show error

# np.uint16 Unsigned integer (0 to 65535)

# np.uint32 Unsigned integer (0 to 4294967295)

# np.uint64 Unsigned integer (0 to 18446744073709551615)
array_b = np.array([-1,0,1],dtype = np.uint16)
print(array_b)    # bcoz negative no. doesnot come in unsigned int16 so "-1" is out of bound and so it shows different no. to show error

# np.float Same as Python's

[ 32766  32767 -32768]
[65535     0     1]


In [39]:
# boolean
test_data = np.array([[1,2,3],[4,5,6],[17,28,39]])
greater_than_five = test_data > 5
print(greater_than_five)
print(test_data[greater_than_five])

[[False False False]
 [False False  True]
 [ True  True  True]]
[ 6 17 28 39]


In [40]:
# where

drop_under_5_array = np.where(test_data > 5 , test_data , 0)
print(drop_under_5_array)

drop_under_5_array2 = np.where(test_data > 5 ,-1 , 0)
print(drop_under_5_array2)

drop_under_5_array3 = np.where(test_data > 5 ,test_data , -1)
print(drop_under_5_array3)

[[ 0  0  0]
 [ 0  0  6]
 [17 28 39]]
[[ 0  0  0]
 [ 0  0 -1]
 [-1 -1 -1]]
[[-1 -1 -1]
 [-1 -1  6]
 [17 28 39]]


In [41]:
# logical_and   (used for 2 conditions)
drop_under_5_and_over_20 = np.logical_and(test_data > 5 , test_data <20)
print(drop_under_5_and_over_20)
print(test_data[drop_under_5_and_over_20])

[[False False False]
 [False False  True]
 [ True False False]]
[ 6 17]


In [42]:
# broadcasting #imp
arr_a = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])  
arr_b = np.array([1,0,1,0])  # this is same as [[1,0,1,0],[1,0,1,0],[1,0,1,0],[1,0,1,0]] + arr_a

print(arr_a + arr_b)

arr_c = np.array([[1],[2],[3]])  # this is same as [[1,1,1,1],[2,2,2,2],[3,3,3,3]]
print(arr_a + arr_c)

[[2 1 2 1]
 [3 2 3 2]
 [4 3 4 3]]
[[2 2 2 2]
 [4 4 4 4]
 [6 6 6 6]]


In [43]:
# for more reference go to official numpy documentation and press ctrl+f to find any command 

# more from documentation quich start


In [44]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [45]:
np.empty((2, 3))

array([[4.24399158e-314, 4.24399158e-314, 8.48798317e-314],
       [8.48798317e-314, 1.27319747e-313, 1.27319747e-313]])

In [47]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print(A * B)     # elementwise product

print(A @ B)     # matrix product

print(A.dot(B))  # another way of  matrix product


[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [50]:
rg = np.random.default_rng(1)  # create instance of default random number generator
b = rg.random((2, 3))
print(b)

[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]


In [52]:
# universal functions
B = np.arange(3)
print(B)

print(np.exp(B)) # e^B

print(np.sqrt(B))

C = np.array([2., -1., 4.])

print(np.add(B, C))  # to add two arrays
# or
print(B + C)        # to add two arrays

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[2. 0. 6.]
[2. 0. 6.]


In [55]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
print(c.shape)

print(c[1, ...])                # same as c[1, :, :] or c[1]
  
print(c[..., 2])               # same as c[:, :, 2]


(2, 2, 3)
[[100 101 102]
 [110 112 113]]
[[  2  13]
 [102 113]]


# spliting one array into equal parts

In [58]:
a = np.floor(10 * rg.random((2, 12)))
print(a)


print(np.hsplit(a, 3))
# # [
#   array([[6., 7., 6., 9.],
#          [8., 5., 5., 7.]]),
#   array([[0., 5., 4., 0.],
#          [1., 8., 6., 7.]]),
#   array([[6., 8., 5., 2.],
#          [1., 8., 1., 0.]])
#   ]

[[1. 0. 8. 8. 8. 4. 2. 0. 6. 7. 8. 2.]
 [2. 6. 8. 9. 1. 4. 8. 4. 5. 0. 6. 9.]]
[array([[1., 0., 8., 8.],
       [2., 6., 8., 9.]]), array([[8., 4., 2., 0.],
       [1., 4., 8., 4.]]), array([[6., 7., 8., 2.],
       [5., 0., 6., 9.]])]


# Different types of copies

In [75]:
# 1)No copy at all
a = np.array([[ 1,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a            # no new object is created
print(b is a)      
b[0,1] = 99     # changes in b(copy) will also be reflected in a(original)
print(a)
print(b)

# 2) shallow copy
print("\n2nd method of copy\n")
c = a.view()
print(c is a)

print(c.base is a)            # c is a view of the data owned by a

print(c.flags.owndata)

c = c.reshape((2, 6))  # a's shape doesn't change
print(a.shape)
print(c.shape)

c[0, 4] = 1234         # a's data changes
print(a)
print(c)

# 3) deep copy
print("\n3rd way of copy\n")

d = a.copy()  # a new array object with new data is created
print(d is a)

print(d.base is a)  # d doesn't share anything with a

d[0, 0] = 9999      # changes made in copy (d here) will only be in d and will not reflected in  original array(a here)
print(a)
print(d)

True
[[ 1 99  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1 99  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

2nd method of copy

False
True
False
(3, 4)
(2, 6)
[[   1   99    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   1   99    2    3 1234    5]
 [   6    7    8    9   10   11]]

3rd way of copy

False
False
[[   1   99    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[9999   99    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [73]:
#Slicing an array returns a view of it:

s = a[:, 1:3]
s[:] = 10         # s[:] is a view of s. Note the difference between s = 10 and s[:] = 10
print(a)

[[   1   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


In [79]:
# indexing again
a = np.arange(5)
print(a)

a[[1, 3, 4]] = 0
print(a)


[0 1 2 3 4]
[0 0 2 0 0]


In [80]:
#However, when the list of indices contains repetitions, the assignment is done several times, leaving behind the last value:

a = np.arange(5)
a[[0, 0, 2]] = [1, 2, 3]
print(a)

[2 1 3 3 4]


In [81]:
#This is reasonable enough, but watch out if you want to use Python’s += construct, as it may not do what you expect:

a = np.arange(5)
a[[0, 0, 2]] += 1
print(a)


[1 1 3 3 4]


In [82]:
#“Automatic” Reshaping
a = np.arange(30)
b = a.reshape((2, -1, 3))  # -1 means "whatever is needed"
b.shape

(2, 5, 3)